services:
  - type: web
    name: multi-platform-video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    preBuildCommand: |
      apt-get update
      apt-get install -y ffmpeg
